relay/relay/urls.py
from django.conf.urls import url
from django.contrib import admin
from mainapp.views import *
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^register$', register, name='register'),
    url(r'^ajax/register/$', ajaxregister, name='ajaxregister'),
    url(r'^login$', login, name='login'),
    url(r'^ajax/login/$', ajaxlogin, name='ajaxlogin'),
    url(r'^$', loginregister, name='loginregister'),
    url(r'^game$', compiler, name='game'),
    url(r'^game1$', abcd, name='game1'),
    url(r'^logout/$', logout, name='logout'),
    url(r'^ajax/runcode/', runcode, name='runcode'),
    url(r'^ajax/savecode/', savecode, name='savecode'),
    url(r'^ajax/swapcode/', swapcode, name='swapcode'),
    url(r'^ajax/submitques/', submitques, name='submitques'),
    url(r'^ajax/finishrace/', finishrace, name='finishrace')
]

relay/mainapp/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models
from ckeditor.fields import RichTextField
import re
from django.core import validators
# Create your models here.


class UserProfile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE) #extending user model
    teamname = models.CharField(max_length=200)
    name = models.CharField(max_length=50)
    idno = models.CharField(max_length=20)
    ip = models.CharField(null=True,max_length=20)

    def __str__(self):
        return self.teamname + "-" + self.idno


class Question(models.Model):
    heading = models.TextField(max_length=200, default='')
    question_text = RichTextField()

    def __str__(self):
        return "Question #" + str(self.pk)

class Team(models.Model):
    user1 = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='user1')
    user2 = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='user2', blank=True, null=True)
    time = models.IntegerField(default=0)
    enable = models.BooleanField(default=True)
    user1q = models.ForeignKey(Question, related_name='user1q', blank=True, null=True)
    user2q = models.ForeignKey(Question, related_name='user2q', blank=True, null=True)
    swap = models.BooleanField(default=False)
    def __str__(self):
        return self.user1.teamname




class Code(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    code = models.TextField(max_length=2000)
    lang = models.IntegerField(default=4)
    swap = models.BooleanField(default=False)

    def __str__(self):
        return self.team.user1.teamname + "-" + str(self.lang)

class GameSwitch(models.Model):
    name=models.CharField(null=False,max_length=10)
    game_active = models.IntegerField(null=False, choices=((0,'0'),(1,'1')),default = 0)

    def __str__(self):
        return self.name

relay/mainapp/forms.py
from django import forms
import re
from django.core import validators

class registerform(forms.Form):
	teamname = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'TeamName'}))

	name = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Name'}))

	password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}),max_length=20)
	password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password Again'}),max_length=20)
	id = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'ID'}))


class loginform(forms.Form):
	password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}),max_length=20)
	id = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'ID'}))

relay/mainapp/views.py
from django.db.models import Q
from django.shortcuts import render, redirect
from django.http import HttpResponse, Http404, HttpResponseRedirect, JsonResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login as authlogin, logout as authlogout
from ipware.ip import get_ip
from django.contrib.auth.decorators import login_required
from random import randint
import requests, json
import time
from.forms import registerform, loginform
from .models import *
import html
from datetime import datetime
# Create your views here.


def ajaxregister(request):
    print("vidit")
    error = ''
    success = False
    register_errors = []
    up = UserProfile.objects.filter(ip=get_ip(request))
    if up.exists()==False:
        print("reached0")
        form = registerform(request.POST)
        reg_errors=json.loads(json.dumps(form.errors))
        for k,v in reg_errors.items():
            if v==['This field is required.']:
                register_errors.append("All fields are required")
            else:
                register_errors.append(v)
            error = register_errors[0]
        if request.method== 'POST':
            if form.is_valid():
                print("1")
                formdata=form.cleaned_data
                if formdata['password1']!=formdata['password2']:
                    error = "Passwords do no match"
                    return JsonResponse({'error': error, 'success': success})

                if User.objects.filter(username=formdata['id']).count()>0:
                    error = "ID already registered"
                elif UserProfile.objects.filter(teamname=formdata['teamname']).count()>1:
                    error = "Teams cannot have more than 2 members"
                else:
                    u = UserProfile.objects.filter(teamname=formdata['teamname'])
                    if u.exists():
                        u1 = u[0].idno
                        user = authenticate(username=u1, password=formdata['password1'])
                        if user is not None:
                            u2 = User(username=formdata['id'])
                            u2.set_password(formdata['password1'])
                            u2.save()
                            u3 = UserProfile(user=u2, teamname=formdata['teamname'], name=formdata['name'], idno=formdata['id'], ip=get_ip(request))
                            u3.save()
                            try:
                                t = Team.objects.get(user1=u[0])
                                t.user2 = u3
                                t.save()
                                success = True
                            except:
                                error = "Something went wrong"
                        else:
                            error = "Password does not match with your teammate"
                    else:
                        u2 = User(username=formdata['id'])
                        u2.set_password(formdata['password1'])
                        u2.save()
                        u3 = UserProfile(user=u2, teamname=formdata['teamname'], name=formdata['name'], idno=formdata['id'], ip=get_ip(request))
                        u3.save()
                        t = Team(user1=u3)
                        t.save()
                        success = True

            else:
                pass
            data = {'error': error, 'success': success}
            print(data)
            return JsonResponse(data)
        else:
            return JsonResponse({'error': "Something went wrong", 'success': success})
    else:
        return JsonResponse({'error': "This PC is already registered", 'success': success})


def register(request):
    return render(request, "register.html", {'form':registerform})

def login(request):
    if request.user.is_authenticated:
        #If user logged in, redirect to home page
        return HttpResponseRedirect('/')
    return render(request, "login.html", {'form':loginform})

def loginregister(request):
    if request.user.is_authenticated:
        #If user logged in, redirect to game
        return HttpResponseRedirect('/game')
    return render(request, "loginregister.html", {'loginform':loginform, 'registerform':registerform})


def ajaxlogin(request):
    print("vidit")
    print(request.POST)
    success = False
    error = ''
    up = UserProfile.objects.filter(ip=get_ip(request))
    print(get_ip(request))
    try:
        t = Team.objects.get(Q(user1=up)|Q(user2=up))
        if t.user2 is None:
            error = "Your teammate hasn't registered"
            return JsonResponse({'error': error, 'success': success})
    except:
        error = "Something happened"
    if up.exists()==True:
        print("reached0")
        form = loginform(request.POST)
        print(form)
        if request.method== 'POST':
            if form.is_valid():
                formdata=form.cleaned_data
                print(formdata)
                username = formdata['id']
                password = formdata['password']
                u = User.objects.filter(username=formdata['id'])
                if u.count()>0 and u[0]!=up[0].user:
                    error = "ID registered from other pc"
                elif u.count()==0:
                    error = "ID not registered"
                else:
                    user = authenticate(username=username, password=password)
                    if user is not None:
                        authlogin(request, user)
                        try:
                            u1 = UserProfile.objects.get(user=user)
                            t = Team.objects.filter(Q(user1=u1) | Q(user2=u1))[0]
                            if t.time<time.mktime(datetime.now().timetuple()):
                                t.time = time.mktime(datetime.now().timetuple())+randint(12*60,17*60)
                                t.save()
                            success = True
                        except:
                            error = "Something went wrong"
                            

                    else:
                        error = "Invalid Password"

            else:
                error = "Invalid ID"
            data = {'error': error, 'success': success}
            print(data)
            return JsonResponse(data)
        else:
            return JsonResponse({'error': "Something went wrong"})
    else:
        return JsonResponse({'error': "This PC is not registered"})


def logout(request):
    try:
        u = UserProfile.objects.get(user=request.user)
        t = Team.objects.get(Q(user1=u) | Q(user2=u))
        t.enable = False
        t.save()
    except:
        pass
    authlogout(request)
    return HttpResponseRedirect('/')


def runcode(request):
    code = request.GET.get('code', None)
    input = request.GET.get('input', None)
    lang = request.GET.get('lang', None)
    langcode = {'4':1, '10':2, '26':3, '36':5, '35':30}
    u = UserProfile.objects.get(user=request.user)
    t = Team.objects.get(Q(user1=u) | Q(user2=u))
    if t.enable==False:
        return JsonResponse({'finish': True})
    lc = str(langcode[lang])
    t = str([str(input)])
    start_time = time.mktime(datetime.now().timetuple())
    try:
        d = {'source': code, 'lang': lc, 'testcases': t,
             'api_key': 'hackerrank|2189697-2296|d21998aae507a388dd24d947e5c07073f8af7e44'}
        print(d)
        r = requests.post('http://api.hackerrank.com/checker/submission.json', data=d)
        print(json.loads(r.text))
        abc = json.loads(r.text)
        print("--- %s seconds ---" % (time.mktime(datetime.now().timetuple()) - start_time))
        data = {
            'compiles': abc["result"]["stderr"]==[False],
        }
        if data['compiles']:
            data['output'] = abc["result"]["stdout"]
        else:
            if abc["result"]["stderr"]==None:
                data['output'] = abc["result"]["compilemessage"]
            else:
                data['output'] = abc["result"]["stderr"]
        print(data)
    except:
        data = {'output': "Some error occured", 'compiles': False}
    return JsonResponse(data)


def swapcode(request):
    code = request.GET.get('code', None)
    lang = request.GET.get('lang', None)
    u = UserProfile.objects.get(user=request.user)
    t = Team.objects.get(Q(user1=u) | Q(user2=u))
    if t.enable==False:
        return JsonResponse({'finish': True})

    if t.user1==u:
        q = t.user1q
    else:
        q = t.user2q
    try:
        cd = Code.objects.get(team=t,question=q)
        cd.code=code
        cd.lang=int(lang)
        cd.swap=True
        cd.save()
    except:
        cd = Code(team=t, question=q, code=code, lang=int(lang), swap=True)
        cd.save()

    print(t.time)

    if t.user1==u:
        a = False
        try:
            c1 = Code.objects.get(team=t,question=t.user1q)
            c2 = Code.objects.get(team=t,question=t.user2q)
            a = c2.swap
        except:
            pass
        while a==False:
            try:
               c2 = Code.objects.get(team=t,question=t.user2q)
               a=c2.swap
            except:
               pass
        (t.user1q, t.user2q) = (t.user2q, t.user1q)
        t.time = time.mktime(datetime.now().timetuple())+randint(900,1200)
        t.swap=True
        t.save()
        c1.save()
        c2.save()
        print("vidit")
        t = Team.objects.get(Q(user1=u) | Q(user2=u))	
        return JsonResponse({'question': c2.question.question_text, 'heading': c2.question.heading, 'code': c2.code, 'lang': c2.lang, 'time': t.time-time.mktime(datetime.now().timetuple())})

    else:
        while t.swap==False:
            try:
                t = Team.objects.get(Q(user1=u) | Q(user2=u))
            except:
                pass

        t.swap=False
        t.save()
        c2 = Code.objects.get(team=t,question=t.user2q)
        c1 = Code.objects.get(team=t,question=t.user1q)
        c2.swap=False
        c1.swap=False

relay/mainapp/templates/login.html
{% load static %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
<script src="{% static 'js/jquery.min.js' %}"></script>
  <title>Login</title>
</head>


<script>
$(document).ready(function(){
	console.log("vidit");
  $("#loginform").submit(function(event) {
  	event.preventDefault();
  	console.log("a");
    $.ajax({
        url: '/ajax/login/',
        data: {
          	'password': $('#id_password').val(),
          	'id': $('#id_id').val(),
        	  csrfmiddlewaretoken: '{{ csrf_token }}'

        	},
        dataType: 'json',
		    type:      'POST',        // 'get' or 'post', override for form's 'method' attribute

        success: function (data) {
            console.log(data.error);
            document.getElementById("errors").innerHTML = data.error;
            if(data.success) {
              window.location = "/";
            } 
        }
      });
  });

  });

</script>



<body>
<h1>Login</h1>

<div id="errors"></div>

<form action="" method="post" id="loginform">
{{form.as_p}}
	{% csrf_token %}
        <input type="submit" value="Submit" id="registersubmit">

</form>
</body>
</html>

relay/mainapp/templates/loginregister.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<title>CODERELAY</title>
		<link type='text/css' rel='stylesheet' href="{% static 'css/loginregister/loginregister.css' %}"/>
		<link rel="stylesheet" type="text/css" href="{% static 'css/montserrat.css' %}"/>
		<script src="{% static 'js/loginregister/loginregister.js' %}"></script>
		<script src="{% static 'js/jquery.min.js' %}"></script>




	</head>
	<body>

<script>
$(document).ready(function(){
	console.log("vidit");
  $("#registerform").submit(function(event) {
  	event.preventDefault();
  	console.log("a");
    $.ajax({
        url: '/ajax/register/',
        data: {
          	'teamname': $('#id_teamname').val(),
          	'password1': $('#id_password1').val(),
            'password2': $('#id_password2').val(),
          	'name': $('#id_name').val(),
          	'id': $('#id_id').val(),
        	csrfmiddlewaretoken: '{{ csrf_token }}'

        	},
        dataType: 'json',
		type:      'POST',        // 'get' or 'post', override for form's 'method' attribute

        success: function (data) {
            console.log(data.error);
            document.getElementById("register_errors").innerHTML = data.error;

            if(data.success) {
              div_transition();
            } 
          
        }
      });
  });

  });

</script>

<script>
$(document).ready(function(){
	console.log("vidit");
  $("#loginform").submit(function(event) {
  	event.preventDefault();
  	console.log("a");
    $.ajax({
        url: '/ajax/login/',
        data: {
        	csrfmiddlewaretoken: '{{ csrf_token }}',
          	'password': $('#id_password').val(),
          	'id': $('#id_id1').val(),

        	},
        dataType: 'json',
		    type:      'POST',        // 'get' or 'post', override for form's 'method' attribute

        success: function (data) {
            console.log(data.error);
            document.getElementById("login_errors").innerHTML = data.error;
            if(data.success) {
              window.location = "/game";
            } 
        }
      });
  });

  });

</script>


	<input type="submit" id="button4" value=" Login "  class="button_class"  style="margin-top:3%; margin-left:90%;padding-left:20px;padding-right:20px;" onclick="div_transition()">
			<div id='title'>
				<h1 id="head"><span style="color:#f1f3f1">CODE</span><span style="color:#111">RELAY</span></h1>
			</div>
			<div id='tag'>
				<p><i>Game that tests blah blah blah</i></p>
			</div>

			<form action="" method="post" id="registerform">

			<div id="loginbox">
			<div id="register_errors" style="margin-left: 30%"></div>
  <div class="logindata" id="logindata1">
    <input type="text" class="form-control" placeholder="Name" id="id_name">
  </div>
    <div class="logindata" id="logindata2">
    <input type="text" class="form-control" placeholder="ID" id="id_id">
  </div>
    <div class="logindata" id="logindata3">
    <input type="text" class="form-control" placeholder="Team Name" id="id_teamname">
  </div>
<div class="logindata" id="logindata4">
    <input type="password" class="form-control" placeholder="Password" id="id_password1">
  </div>
<div class="logindata" id="logindata5">
    <input type="password" class="form-control" placeholder="Password Again" id="id_password2">
  </div>
  	{% csrf_token %}

   <input type="submit" id="register" value=" Register "  class="button_class">
    <!--  <p class="register">Already Registered?</p><input type="submit" id="button4" value=" Login "  class="button_class"  style="margin-top:0%; margin-left:60%" onclick="">
	--></div>
	</form>

	<form action="" method="post" id="loginform">
	<div id="loginbox2">
				<div id="login_errors" style="margin-left: 30%"></div>

     <div class="logindata" id="logindata2">
    <input type="text" class="form-control" placeholder="ID" id="id_id1">
  </div>
  <div class="logindata" id="logindata4">
    <input type="password" class="form-control" placeholder="Password" id="id_password">
  </div>
    	{% csrf_token %}

   <input type="submit" id="login" value=" Get Started "  class="button_class">
   </form>

   <p class="register">Haven't Registered yet ?<input type="button" id="button3" value=" Register " 
   class="button_class" onclick="div_transition2()"></p>
	</div></span>
	</body>
	</html>
	
	

relay/mainapp/templates/register.html
{% load static %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
<script src="{% static 'js/jquery.min.js' %}"></script>
  <title>Register</title>
</head>


<script>
$(document).ready(function(){
	console.log("vidit");
  $("#registerform").submit(function(event) {
  	event.preventDefault();
  	console.log("a");
    $.ajax({
        url: '/ajax/register/',
        data: {
          	'teamname': $('#id_teamname').val(),
          	'password1': $('#id_password1').val(),
          	'password2': $('#id_password2').val(),
          	'id': $('#id_id').val(),
        	csrfmiddlewaretoken: '{{ csrf_token }}'

        	},
        dataType: 'json',
		type:      'POST',        // 'get' or 'post', override for form's 'method' attribute

        success: function (data) {
            console.log(data.error);
            document.getElementById("errors").innerHTML = data.error;
            if(data.success) {
              window.location = "/login";
            } 
          
        }
      });
  });

  });

</script>



<body>
<h1>Register</h1>

<div id="errors"></div>

<form action="" method="post" id="registerform">
{{form.as_p}}
	{% csrf_token %}
        <input type="submit" value="Submit" id="registersubmit">

</form>
</body>
</html>

relay/mainapp/templates/register1.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>Register</title>
</head>
<script>
$(document).ready(function(){

  $("#registersubmit").click(function(e) {
  	  	console.log("vidit");

  	event.preventDefault();
    $.ajax({
        url: '/ajax/register/',
        data: {
          'teamname': $('#id_teamname').val(),
          	'password1': $('#id_password1').val(),
          	'password2': $('#id_password2').val(),
          	'id': $('#id_id').val(),
        },
        dataType: 'json',
        success: function (data) {
            console.log(data);
               
        }
      });


  });
  });

</script>
<!--<script>
$(document).ready(function(){

  	$("#registersubmit").click(function(event) {
		event.preventDefault();
		console.log("vidit");
    	$.ajax({
        	url: '/ajax/register/',
        	data: {
          	'teamname': $('#id_teamname').val(),
          	'password1': $('#id_password1').val(),
          	'password2': $('#id_password2').val(),
          	'id': $('#id_id').val(),

        	},
        	dataType: 'json',

        	success: function (data) {
            	console.log(data);
            	document.getElementById("errors").innerHTML = data.error
        	}
      	});

  	});
  });

-->
<body>
<h1>Register</h1>

<div id="errors"></div>

<form action="" method="post" id="registerform">
	{% csrf_token %}
        <input type="submit" value="Submit" id="registersubmit">
</form>
</body>

</html>